export const GET_HOTEL_REQUEST = "GET_HOTEL_REQUEST";
export const GET_HOTEL_SUCCESS = "GET_HOTEL_SUCCESS";
export const GET_HOTEL_FAILURE = "GET_HOTEL_FAILURE";

export const POST_HOTEL_REQUEST = "POST_HOTEL_REQUEST";
export const POST_HOTEL_SUCCESS = "POST_HOTEL_SUCCESS";
export const POST_HOTEL_FAILURE = "POST_HOTEL_FAILURE";
export const CART_VALUE = "CART_VALUE";

export const GET_HOTEL_DETAILS_REQUEST = "GET_HOTEL_REQUEST";
export const GET_HOTEL_DETAILS_SUCCESS = "GET_HOTEL_SUCCESS";
export const GET_HOTEL_DETAILS_FAILURE = "GET_HOTEL_FAILURE";